# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea5b3efd14b0c81ffdf8b1c7bca9d065b778445ae9cb7a530c1c592ebacd469ba77d22594493146a26b2f7f2bb1620caa6a1543a3460b014f830f09983f8e89b

test:
  secret_key_base: 2c430c7106cb51965311c07a48e10ec42537449d4c5dfcb86765cab57c6db420a0a8b5a3a009b2e559d77466ccb4fbd353e097784ac08667074da3c0ced77ba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
